use std::{cell::RefCell, rc::Rc};

use crate::{
    message::Message,
    parse::{PMessage, UnixTimestamp},
};

/// This class handles all the messages in a channel, either processed or not.
/// Responsible for receiving PMessage objects (parser messages) and generate groups of messages (PMessageGroup)
/// to be processed into Message's
/// We want to process messages in groups because it makes more accurate some analysis (e.g. language detection).
/// The group of messages generated by this class are sent by the same author, in chronological order.
///
/// We have to deal with messages from different files (exports) that may have different starting times
/// for the same channel, and even overlapping periods. So this class solves all that.
/// We have the concept of intervals, where each interval (a [`MessagesInterval`] instance) stores messages from
/// a starting time to an ending time.
///
/// ❗ This class assumes that messages are added in chronological order, unless they are separated by a `mark_eof` call.
/// This way it can deal with out-of-order (between `mark_eof` calls) and duplicated messages.
///
/// If a message with a timestamp that is contained in an existing interval is added (but not previously already),
/// it will be dropped (not that common, e.g. different exports with deleted messages)
///
/// After all the processing is done, processed messages can be iterated via `*processedMessages()` in the
/// correct chronological order.
///
/// Note: in the future, we may want to process PMessage into IMessage's (some kind of intermediate messages) instead of
///       just Message, so we can pass intermediate information not needed for the final Message. This will require
///       refactoring the MessagesArray class.
#[derive(Default)]
pub struct ChannelMessages {
    /// All intervals found until now. Chronologically sorted.
    intervals: Vec<Rc<RefCell<MessagesInterval>>>,

    /// Currently open interval. Next messages will be stored here
    open_interval: Option<Rc<RefCell<MessagesInterval>>>,
}

impl ChannelMessages {
    /// Adds a PMessage to the pending messages to processed in the current open interval.
    /// If there is no open interval, a new one will be created with the given message.
    pub fn add_message(&mut self, message: PMessage) {
        // first we have to make sure that extending the open interval (or a new one) will not overlap with other intervals
        for interval in &self.intervals {
            if interval.borrow().is_contained(message.timestamp) {
                // drop duplicate message, already included in another interval
                return;
            }
        }

        if let Some(open_interval) = &mut self.open_interval {
            // there is an open interval, we should be able to add this message to it without problems
            open_interval.borrow_mut().add_message_and_extend(message);
        } else {
            // create a new interval
            let interval = Rc::new(RefCell::new(MessagesInterval::new(message)));

            self.open_interval = Some(interval.clone());

            // add and make sure intervals stay chronologically sorted
            self.intervals.push(interval);
            self.intervals
                .sort_by(|a, b| a.borrow().start.cmp(&b.borrow().start));
        }
    }

    /// Mark the end of an input file. This allows the next message added (from another file)
    /// to have a different starting timestamp.
    ///
    /// It will close the current open interval, if any. Make sure to call `process` to process leftover messages.
    pub fn mark_eof(&mut self) {
        self.open_interval = None;
    }
}

/// This class represents a list of messages contained in a time interval.
/// Messages stored here can be either pending to be processed or already processed. (PMessage → Message)
/// Unprocessed messages (PMessage) are added via `addAndExtend(message)`. Eventually you
/// should call `process(fn, isClosed)` to process all pending messages (into Message).
/// The processing is not done by this class; instead you are expected to provide a function to process
/// groups of messages into Message's.
/// These groups of messages are PMessageGroup and are guaranteed to be from the same author, in chronological order.
/// The `isClosed` parameter is used to indicate that the interval is closed and no more messages will be added, to
/// allow process the leftover.
///
/// It also keeps track of the index of each message by its ID.
pub struct MessagesInterval {
    /// [start, end]
    start: UnixTimestamp,
    end: UnixTimestamp,

    /// Messages pending to be grouped and processed. It should be very few elements here at a time
    message_queue: Vec<PMessage>,

    /// Messages already processed.
    messages: Vec<Message>,
}

impl MessagesInterval {
    pub fn new(initial_message: PMessage) -> Self {
        Self {
            start: initial_message.timestamp,
            end: initial_message.timestamp,
            message_queue: vec![initial_message],
            messages: Vec::new(),
        }
    }

    /// Adds the PMessage to the queue and extends the end of the interval to contain it
    pub fn add_message_and_extend(&mut self, message: PMessage) {
        if message.timestamp < self.end {
            panic!("MessagesInterval can only be extended to the future");
        }

        self.end = message.timestamp;
        self.message_queue.push(message);
    }

    pub fn is_contained(&self, ts: UnixTimestamp) -> bool {
        ts >= self.start && ts <= self.end
    }
}
